### ISSUE TITLE
Microcontroller Change

### ISSUE THREAD

**Issue by Aeasala** [Pablo-Ortiz-Lopez/DSKY#12]
https://es.aliexpress.com/item/1005006053215107.html

**Comment by Pablo-Ortiz-Lopez** [comment]
After some analysis, the initial microcontroller board chosen (Arduino UNO), is deemed to be too big to fit in the area below the keys, where it's supposed to be placed. It is because of this that I propose switching to an Arduino Micro board.

The Arduino Micro is essentially a shrunk down Arduino UNO, without sacrificing any functionality that is needed for this project. 
If there is no objection I shall update the branch #8 to use this board instead.

**Comment by Aeasala** [comment]
New uC implemented as of https://github.com/Pablo-Ortiz-Lopez/DSKY/pull/8 & https://github.com/Pablo-Ortiz-Lopez/DSKY/issues/7

**Comment by Aeasala** [comment]
New uC implemented as of PR https://github.com/Pablo-Ortiz-Lopez/DSKY/pull/8 & Issue https://github.com/Pablo-Ortiz-Lopez/DSKY/issues/7
