### ISSUE TITLE
Alarm Lights PCB Work

### ISSUE THREAD

**Issue by Aeasala** [Pablo-Ortiz-Lopez/DSKY#5]
for alarm board

**Comment by Pablo-Ortiz-Lopez** [comment]
While the current state of the PR would satisfy the minimum requirement of a functional alarm board, I believe improvement is possible on the following two issues:

- The JST header should be parallel to one of the main board's I2C headers, and the pins lined up so that a straight path between them is achieved, and minimal twisting of the connector is needed to join both boards
- There should be a separate power rail, specifically to feed the LED's, so that the board can be driven with an independent power rail from the one used for the uno's 5V logic. This would allow for PWM and higher voltages to be applied on the LED's.
